name: Build and Release Android APK

on:
  push:
    tags:
      - 'v*'   # Only run when pushing a tag like v1.0.0

permissions:
  contents: write   # Needed for creating GitHub Releases

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # 4. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 5. Build release APK
      - name: Build APK
        run: flutter build apk --release

      # 6. Upload to GitHub Release
      - name: Upload Release APK
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
